# Generated by Django 4.2.23 on 2025-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_bb', '0082_remove_bigbrotherconfig_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papsconfig',
            name='max_corp_paps',
            field=models.PositiveIntegerField(default=1, help_text='How many Corp PAPs will count?'),
        ),
    ]
