# Generated by Django 4.2.21 on 2025-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_bb', '0093_eveitemprice_delete_bigbrotherredditmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigbrotherconfig',
            name='clone_state_always_recheck',
            field=models.BooleanField(default=False, help_text='If enabled, characters with a known skill proving their Alpha/Omega state will always be re-checked, bypassing the cache TTL, and potentially catching state changes far quicker. Disabling this can significantly improve performance.', verbose_name='Clone State: Always Re-check Proven Skills'),
        ),
    ]
